apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksclusterdominik-9ca8"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksclusterdominik-9ca8"
  template:
    metadata:
      labels:
        app: "aksclusterdominik-9ca8"
    spec:
      containers:
        - name: "aksclusterdominik-9ca8"
          image: "aksregisterydominik.azurecr.io/aksclusterdominik"
          ports:
          - containerPort: 80