apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksclusterdominik02-75c9"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksclusterdominik02-75c9"
  template:
    metadata:
      labels:
        app: "aksclusterdominik02-75c9"
    spec:
      containers:
        - name: "aksclusterdominik02-75c9"
          image: "aksregisterydominik2.azurecr.io/aksclusterdominik02"
          ports:
          - containerPort: 80