apiVersion: v1
kind: Service
metadata:
    name: "aksclusterdominik02-75c9"
    labels:
        app: "aksclusterdominik02-75c9"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksclusterdominik02-75c9"