on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: aksregisterydominik.azurecr.io
        username: ${{ secrets.acr_aksregisterydominik_username }}
        password: ${{ secrets.acr_aksregisterydominik_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t aksregisterydominik.azurecr.io/aksclusterdominik:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push aksregisterydominik.azurecr.io/aksclusterdominik:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksclusterdominik_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-dominik-namespace | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-dominik-namespace`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-dominik-namespace
        container-registry-url: aksregisterydominik.azurecr.io
        container-registry-username: ${{ secrets.acr_aksregisterydominik_username }}
        container-registry-password: ${{ secrets.acr_aksregisterydominik_password }}
        secret-name: aksclusterdodockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-dominik-namespace
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          aksregisterydominik.azurecr.io/aksclusterdominik:${{ github.sha }}
        imagepullsecrets: |
          aksclusterdodockerauth
